services:
  app:
    build:
      context: .
    image: miapp:latest
    ports:
      - "9090:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    volumes:
      - ./application-docker.yml:/app/application-docker.yml